### ISSUE TITLE
Incorrect license

### ISSUE THREAD

**Issue by andrew** [doowb/octobox.js#1]
Nice work on the rewrite of octobox but as you're using html, css and the logo from the original project you must abide by the same license which is AGPL 3: https://github.com/octobox/octobox/blob/master/LICENSE.txt

**Comment by BenJam** [comment]
Boo...

**Comment by lhaig** [comment]
Mmm

**Comment by doowb** [comment]
Thanks for pointing this out. Sorry I missed that. Would you do a PR to update the appropriate sections? I'll review and merge when I get home.
